### ISSUE TITLE
Navigation side bar and links

### ISSUE THREAD

**Issue by dan5382** [returntocorp/semgrep-docs#113]
Last week we had worked to change the sidebar design. We changed the colors used in the background. we also changed our global link color.

for reference: 
Nav background color- #29343D
Link color- #359DFD
 
can we have it back?

**Comment by pabloest** [comment]
@dan5382 @sabihb mind if I take this? I am about to submit a PR to address an issue @mschwager pointed out and it’s easy for me to make the change.

**Comment by dan5382** [comment]
I think Sabrina already did the work; so maybe we check in with her real quick?

**Comment by sabihb** [comment]
Yes this is done! I'm not sure how to deploy changes to the docs, but the PR (https://github.com/returntocorp/semgrep-docs/pull/110) has been merged and when I run mkdocs on the develop branch, I see the theme change. So it's just a matter of getting those changes up to semgrep.dev/docs.
