### ISSUE TITLE
Document how to set policies for project & what default policy means

### ISSUE THREAD

**Issue by underyx** [returntocorp/semgrep-docs#119]
A user reported confusion around this topic. Wasn't sure if there's any way to set a policy other than making it default. I checked our docs and seems like we don't say anything about the projects page.

tagging @dlukeomalley and @chmccreery (as you implemented multi-policy, which probably needs a two-sentence explanation itself.)

**Comment by chmccreery** [comment]
Agreed, I will work on documenting this for now, and we should also figure out how to improve the UI (this feels like something people shouldn't really _need_ docs for)

**Comment by dlukeomalley** [comment]
+1! @chmccreery - @dan5382 is starting to prioritize UI/UX work and I think this is on his radar. Commenting here to make sure we connect you two.

**Comment by chmccreery** [comment]
Specific request from the user:
Change the way policy is displayed on the _projects_ page, because it doesn't look particularly editable. You have to know to mouse over it to see that it is editable.
