### ISSUE TITLE
Add playground link for each example

### ISSUE THREAD

**Issue by mschwager** [returntocorp/semgrep-docs#120]
We provide lots of examples in the [pattern syntax](https://semgrep.dev/docs/writing-rules/pattern-syntax/) and [rule syntax](https://semgrep.dev/docs/writing-rules/rule-syntax/) pages. It would be awesome if each of these examples had an accompanying link to a playground snippet with the code + pattern filled out. That would allow users to quickly play around with our docs examples :+1: 

At some point it may make sense to have a small, embeddable version of the editor that we can simply iframe in the docs examples and can be run from there. Until then, this is a step in that direction.

**Comment by sabrinabrogren** [comment]
Oh wow totally forgot about this ticket, thanks for cleaning up @ievans !
