### ISSUE TITLE
Add Testing Rules section to Writing Rules

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/semgrep-docs#22]
From @msorens on the r2c [community Slack](https://r2c-community.slack.com/archives/CK86BJ5DW/p1603983898368900):

> Read an interesting thread above about // ruleid which I had not encountered before. So I then went to read about it in the docs but not able to find it. :pouting_cat: Could someone point me to info on it?

This documentation currently is available at https://github.com/returntocorp/semgrep-rules#testing-rules, but may fit nicely in the Writing Rules section of our documentation.

This section may also be an opportunity to discuss our rules template and [Awesome Rulesets](https://semgrep.dev/docs/awesome/).

**Comment by mschwager** [comment]
Hi @msorens,

I wanted to let you know that our new "Testing rules" docs are live: https://semgrep.dev/docs/writing-rules/testing-rules/
