### ISSUE TITLE
Weird header behavior with Ctrl + F

### ISSUE THREAD

**Issue by mschwager** [returntocorp/semgrep-docs#243]
When I use ctrl + f to search within in a page it moves the docs header to the middle of the page:

![header](https://user-images.githubusercontent.com/1724818/128514975-591c0127-cd5b-4a6d-8aac-869961670e7c.gif)

**Comment by pabloest** [comment]
Thanks for the report, @mschwager. Very strange. This is in Firefox, yes? If so, what version are you using and can you try the same ctrl+f using a private browser window or one with no 3rd party extensions? I was unable to reproduce on Firefox 90.0.2 (on a Mac).

**Comment by mschwager** [comment]
Huh, weird. Yup Firefox 90.0.2 on Linux. Same behavior in a private window with no extensions.

Either way, not a huge deal. Especially if it's just on my esoteric machine.

**Comment by pabloest** [comment]
Thanks for confirming. OK, let’s just leave this open for now and see if anyone else is affected.

**Comment by n-hebert** [comment]
This is happening for me on Firefox 91.0.2, Linux x64

It doesn't need CTRL+F here, though. It happens on any scroll :slightly_smiling_face: 

https://user-images.githubusercontent.com/68243838/131731990-c66a6eae-781f-4303-b87b-9c876ff6598f.mp4

**Comment by pabloest** [comment]
Thanks for your report, @n-hebert! I see the same now on Firefox 91.0.2 on my Mac (v10.15.7). I’ll look into it further.
