### ISSUE TITLE
Can't search from docs

### ISSUE THREAD

**Issue by raghavjain3** [returntocorp/semgrep-docs#271]
Repro steps:

1. Navigate to https://semgrep.dev/docs
2. Search for something in the search bar
3. Press enter / click the suggested result
4. URL changes to https://semgrep.dev/docs/#docusaurus-base-url-issue-banner-container and page does not navigate anywhere

**Comment by pabloest** [comment]
This seems to be related to searching for names of some programming languages, like Kotlin, Lua, Rust, etc.

**Comment by pabloest** [comment]
Looks like this is fixed by PR #272
