### ISSUE TITLE
Old docs still lives and cached

### ISSUE THREAD

**Issue by adamboros** [returntocorp/semgrep-docs#292]
I suspect that the old docs still live in the server, where it was not overwritten by Docusaurus. 
One example is [CLI reference](https://semgrep.dev/docs/cli-reference/) which is still cached by Google. 
The [new page](https://semgrep.dev/docs/cli-usage/) has an URL named CLI usage, but the page title is still CLI reference.

**Comment by s-santillan** [comment]
@pabloest Is there something either Adam or I can do about this issue? (Just not sure if we have permission to handle the redirects).

**Comment by pabloest** [comment]
@s-santillan Yes :) All that’s needed is to add a line to `docusaurus.config.js` for the redirect. Redirects are configured starting at line 171 in that file.

**Comment by s-santillan** [comment]
I am linking a PR here but when I try it on my local, it doesn't redirect. Yarn compiles successfully, docs work, but when I test the redirecting by typing in docs/cli-reference/, it doesn't redirect to docs/cli-usage. Attaching screenshot.


![2021-12-23 02_37](https://user-images.githubusercontent.com/20766840/147139874-08839403-8345-4941-8550-98af98b7b4e7.png)

**Comment by s-santillan** [comment]
For Pablo: Do you think we may have more redirects/old links to find? Should I make a task for it?

**Comment by pabloest** [comment]
I think this is because the redirect only works on the production build, not on the development build/process. To test it, try running `yarn build` and then `yarn serve`, and then try the old link (your localhost’s port will be different). It should redirect to the new one.

I’m not aware of any other old links we need to redirect.

**Comment by s-santillan** [comment]
@pabloest it works! Thank you :)
