### ISSUE TITLE
Dollar($) sign gets copied with commands

### ISSUE THREAD

**Issue by niraj8** [returntocorp/semgrep-docs#355]
While copying cli commands, the `$` is copied with the command.

We could remove the `$` from commands that are meant to be copied, like [this section](https://semgrep.dev/docs/contributing/contributing-code/#development-workflow)

**Comment by s-santillan** [comment]
@niraj8 Thanks for bringing this up! Since [PR 440](https://github.com/returntocorp/semgrep-docs/pull/440) this issue has been resolved.
