### ISSUE TITLE
Plural of ellipsis is ellipses

### ISSUE THREAD

**Issue by pieterdc1** [returntocorp/semgrep-docs#490]
English is not my native language, but I think this is used incorrectly a few times. E.g. under Ellipsis Metavariables 

I think
> You can combine ellipsis and metavariables to match

should be

> You can combine ellips**e**s and metavariables to match

Similarly,
under Function definitions
> In that case you can use ellipsis in place of the name

should be

> In that case you can use **an** ellipsis in place of the name

**Comment by s-santillan** [comment]
@pieterdc1 I'll look into it! Thank you!

**Comment by adamkvitek** [comment]
Hello @s-santillan and @pieterdc1. Thanks for this! Started a PR here, have you seen this issue anywhere else? It looked ok except for the two things you mentioned Pieter. :-) https://github.com/returntocorp/semgrep-docs/pull/513
