### ISSUE TITLE
Has slack invite link expired?

### ISSUE THREAD

**Issue by tghosth** [returntocorp/semgrep-docs#545]
Getting an error when trying to open the slack link in the docs 
https://r2c.dev/slack
![image](https://user-images.githubusercontent.com/13623828/169274056-7585b40e-386a-4423-a025-7f0618408362.png)

**Comment by s-santillan** [comment]
@tghosth Hi Josh! Thanks for alerting us. We tested this out on our desktops, in chrome/firefox, and within incognito and regular browsing. The link is still active (at least on our end). However, we did replicate this issue on mobile. Maybe you could try on desktop?

**Comment by tghosth** [comment]
Thanks, looks like that now works on both desktop and mobile now.
