### ISSUE TITLE
Navigation sidebar sections should be more clearly defined, easier to scan, and perhaps simplified

### ISSUE THREAD

**Issue by pabloest** [returntocorp/semgrep-docs#87]
Follow up to some of the discussion here: https://github.com/returntocorp/semgrep-docs/pull/85

Here’s one idea that partially addresses the groupings comments but doesn’t combine pages like the rule and pattern syntax pages:

![Screen Shot 2021-02-03 at 9 56 26 AM](https://user-images.githubusercontent.com/302941/106788710-2a460180-6606-11eb-8b84-8e007c1967c1.png)

cc @chmccreery @mschwager @dlukeomalley @underyx

**Comment by chmccreery** [comment]
I think what is confusing to me is how the sidebar, the list of blue links under "Semgrep" and the list of links under "Overview" are related. 

It seems like they ought to somehow be nested/overlapping, such as:

Sidebar: Overview, Getting Started, Writing Rules, Pattern Syntax, Rule Syntax, Running Rules, Semgrep CLI, Managing CI, Integrations,  Experiments
Semgrep (subset of sidebar with only broadest categories): Writing Rules, Running Rules, Managing CI
Overview: Description of product without linking to other places directly 

Essentially, my suggestion would be: 
- Come up with a nesting of titles/subtitles that make sense with one layer of depth 
- Flatten this and put them all in the sidebar
- Put only the titles under "Semgrep" on homepage of Docs
- Put subtitle links at top of each title page

**Comment by pabloest** [comment]
Thanks for the thoughtful comment, @chmccreery. 

I see what you mean about the overview page’s table of contents. @dlukeomalley and I are planning to revamp this getting started/overview page and we’ll definitely take that into account. We’ll also work on the nesting.

**Comment by pabloest** [comment]
I started to work on this and I’m thinking we could remove the table-of-contents-style thing in the overview page itself. The sidebar is already there for nav, so do we really need a nav-like thing on the getting started page? I’m also thinking about how to make room for the 1-2-3 steps that we want to convey to people (that’s not in the screenshot below).

![Screen Shot 2021-02-04 at 10 46 06 AM](https://user-images.githubusercontent.com/302941/106940498-76f90d80-66d6-11eb-9f6b-2aca8af5f2e8.png)

**Comment by pabloest** [comment]
Related PR: https://github.com/returntocorp/semgrep-docs/pull/91
